// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnUuoSwTIIxVj_6yfqJ-V-091cBZX5Ecw',
    appId: '1:776932367693:web:c32350ecea9ca2beecab04',
    messagingSenderId: '776932367693',
    projectId: 'flutter-auth-test-a2f57',
    authDomain: 'flutter-auth-test-a2f57.firebaseapp.com',
    storageBucket: 'flutter-auth-test-a2f57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzIcDIlceB_6M_KrE4O2CKDbQGQekzJSA',
    appId: '1:776932367693:android:04c295806e2bfeeaecab04',
    messagingSenderId: '776932367693',
    projectId: 'flutter-auth-test-a2f57',
    storageBucket: 'flutter-auth-test-a2f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6fGyWZqNS4S3m5l4dMBEKcyMJitZFNXI',
    appId: '1:776932367693:ios:695e1731f721116cecab04',
    messagingSenderId: '776932367693',
    projectId: 'flutter-auth-test-a2f57',
    storageBucket: 'flutter-auth-test-a2f57.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6fGyWZqNS4S3m5l4dMBEKcyMJitZFNXI',
    appId: '1:776932367693:ios:caed91f5b43bfecbecab04',
    messagingSenderId: '776932367693',
    projectId: 'flutter-auth-test-a2f57',
    storageBucket: 'flutter-auth-test-a2f57.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
